### ISSUE TITLE
Sync with npm

### ISSUE THREAD

**Issue by liqwid** [davidstutz/bootstrap-multiselect#767] opened 2016-07-14 15:15 UTC
`npm install bootstrap-multiselect` currently installs version 0.9.16 which is bigger than github version. It also doesn't have fix #709 included.

Please update npm version to have all the bugfixes from github and downgrade it's version(or merge them if they have had diverged)

**Comment by davidstutz** [comment] 2016-07-21 17:47
Yes, will come with the next release.

**Comment by davidstutz** [comment] 2017-10-24 18:54
Duplicate of #667 .

**Closed by davidstutz** 2017-10-24 18:54 UTC
Labels: bug
