### ISSUE TITLE
Automatically focus on filterBox when enableFiltering: true

### ISSUE THREAD

**Issue by kokizzu** [davidstutz/bootstrap-multiselect#153] opened 2013-09-18 05:06 UTC
Automatically focus on filterBox when enableFiltering: true
so when user click or use spacebar, the caret would focus on filterBox, because pressing Tab button would make it lose focus

**Comment by niyazpk** [comment] 2015-11-10 22:53
Duplicate of #615

**Closed** 2021-03-15 03:04 UTC
Labels: enhancement
