### ISSUE TITLE
Report an issue: incorrect selected item number 

### ISSUE THREAD

**Issue by soyosolution** [davidstutz/bootstrap-multiselect#545] opened 2015-05-21 04:58 UTC
The issue was found  with `Bootstrap 3` & `jquery 1.11.2`
When clicking "select all" and then un-select a few items, it would keep showing 5 selected (the right total selected items number is 3)

![problem00](https://cloud.githubusercontent.com/assets/5309660/7741651/79dcc06c-ffb4-11e4-993a-e6b2e7fa777d.PNG)

Continue with this case, if I re-select some of the items again (but not all items), The text would show "All selected (6)"
![problem01](https://cloud.githubusercontent.com/assets/5309660/7741652/7ddf77ae-ffb4-11e4-9ea4-ed9ef477484b.PNG)

Here is my code for the case:
## JavaScript

```
<script type="text/javascript">
    $(function () {
        $('#skill-filter').multiselect({ includeSelectAllOption: true });
    });
</script>
```
## HTML

```
<select id="skill-filter" title="Skill" name="skill" class="form-control" multiple="multiple">
    <option value="indo">Skill 1</option>
    <option value="fili">Skill 2</option>
    <option value="fili">Skill 3</option>
    <option value="fili">Skill 4</option>
    <option value="fili">Skill 5</option>    
    <option value="fili">Skill 6</option>        
</select>
```

Update at 15:08pm 21st May,2015 for adding an existing live example on internet: 
http://jsfiddle.net/StephenEdmondson/TR49m/4/

![problem02](https://cloud.githubusercontent.com/assets/5309660/7743244/7f00105a-ffcb-11e4-946b-519aad255daa.PNG)

**Comment by davidstutz** [comment] 2015-05-24 22:06
Please, if you have a fix for this, share it. I will probably not look into this, as I am not familiar with Knockout JS.

**Comment by bkwdesign** [comment] 2015-06-24 16:23
I can reproduce this bug by playing with [your demo site](http://davidstutz.github.io/bootstrap-multiselect/#methods)
![multiselect-demo](https://cloud.githubusercontent.com/assets/3177513/8335299/dc779d2a-1a6a-11e5-85e2-5ae2eb0e54d4.jpg)

Scroll to the block explaining *.multiselect('refresh')*

**Comment by ekinhbayar** [comment] 2015-09-09 00:11
I had the same issue when using 6 different selects on a page, was able to fix this by using the 'rebuild' method as below:

    $(document).ready(function() {
           $('#sample').multiselect();
           $('#sample').change(function(){
                if($(this).val() !== '') {
                    $('#sample').multiselect('rebuild');
                }
            });
     });

**Comment by davidstutz** [comment] 2015-10-15 22:30
I am sorry, but I still cannot reproduce this error. @bkwdesign or @ekinhbayar can you give detailed instructions on how to reproduce the error? Please also include your setup, browser, etc ...

**Closed** 2017-10-23 17:59 UTC
Labels: bug
