### ISSUE TITLE
Add option to focus search input on dropdown open

### ISSUE THREAD

**Issue by Dacesilian** [davidstutz/bootstrap-multiselect#615] opened 2015-08-27 16:57 UTC
I suggest to add an option to focus search input on dropdown open. Working workaround is:

    onDropdownShown : function(event) {
    	$('#select').parent().find("button.multiselect-clear-filter").click();
    	$('#select').parent().find("input[type='text'].multiselect-search").focus();
    }

**Comment by rkhayat** [comment] 2015-10-09 15:07
:+1:

**Comment by styfle** [comment] 2015-11-10 23:15
:+1:

**Comment by davidstutz** [comment] 2016-07-19 17:53
Duplicate of #615. In the meantime, added the workaround to the FAQ.

**Closed** 2016-07-19 17:57 UTC
Labels: enhancement

**Comment by Imekhan** [comment] 2017-04-06 11:44
@Dacesilian great work, but if there are multiple dropdown on page then do like below:

               onDropdownShown : function(event) {
			this.$select.parent().find("button.multiselect-clear-filter").click();
			this.$select.parent().find("input[type='text'].multiselect-search").focus();
		}

**Comment by baladkb** [comment] 2018-08-03 12:51
Hi folks, below code works for me, please check. 
```
onDropdownShown : function(event) {
setTimeout(function(){
$('#select').parent().find("button.multiselect-clear-filter").click();
$('#select').parent().find("input[type='text'].multiselect-search").focus();
}, 100);
}
```
thanks!

**Comment by UseMuse** [comment] 2019-12-06 11:39
@baladkb thx, its work for me
