### ISSUE TITLE
fixed search box

### ISSUE THREAD

**Issue by smart--petea** [davidstutz/bootstrap-multiselect#396] opened 2014-10-07 07:16 UTC
1. I have a lot of items
2. I setted max height
3. search is enabled
4. when I'm scrolling the items the search box is scrolled too.

Can I fix search box in some way?

**Comment by n8thegr8** [comment] 2015-07-02 18:20
Was this ever fixed?

**Comment by szegediistvan** [comment] 2015-08-08 09:28
This feature is important for me, furthermore the "select all" line could be in fixed position as well.

**Comment by raunaq-itmatrix** [comment] 2015-08-18 13:57
You can add your own class and apply style like below in order to fix the search box.

.fixedHeader-ul
{
    overflow-x: scroll;
}
.fixedHeader-ul li
{
}
.fixedHeader-ul li:first-child
{
    position: fixed;
    background-color: white;
    z-index: 10;
    
}

**Comment by davidstutz** [comment] 2015-10-15 22:34
@n8thegr8 no this was never really fixed. Further, the solution given by @raunaq-itmatrix does not work for me.

**Comment by szegediistvan** [comment] 2015-10-16 14:55
@raunaq-itmatrix your solution doesn't work for me, any other solution?

**Comment by raunaq-itmatrix** [comment] 2015-10-19 15:09
@n8thegr8  @szegediistvan If you can create JSFiddle, I'll look at it and try to help you on that.

**Comment by szegediistvan** [comment] 2015-10-21 13:08
@raunaq-itmatrix This is my Codepen:
http://codepen.io/szegediistvan/pen/xwpmzz

Please help me, because i need fixed search box solution.

**Comment by raunaq-itmatrix** [comment] 2015-10-23 14:29
@szegediistvan 

Add following class to your CSS and you are all set ! You just need take care of padding/margin.
.input-group
{
  position:fixed;
  z-index:100;
  width:337px;
  background-color:white;
  padding:10px;
}

**Comment by raunaq-itmatrix** [comment] 2015-10-28 17:08
@szegediistvan  Is above provided solution worked for you?

**Comment by szegediistvan** [comment] 2015-11-04 08:23
No. I would like to fixing li.multiselect-item.filter element, when the options were opened.

**Comment by amicel** [comment] 2016-06-10 08:15
You could wrap all the options except filter with some div for custom styling. This worked for me: https://jsfiddle.net/101Lucho/1/
Further, you could add that code to **onInitialize** configuration option.

**Comment by mroeling** [comment] 2016-07-22 06:57
@amicel Confirmed! Perfect working solution. And indeed, oninitialized works properly, too.

> onInitialized: function(select, container) {
>             $('.multiselect-container').find('li:not(.multiselect-filter)').wrapAll('&lt;div class="options-wrapper"></div>');
>         }

**Comment by richrd** [comment] 2016-08-30 15:11
Hey, I have this problem too! Wishing the filter would stay fixed to the top. I'd assume this would be how most people would like it to work.

What if I make pull request for this feature, would you be open to changing the default behaviour @davidstutz ?

**Comment by phuctma** [comment] 2017-06-25 16:02
I have a workaround. We can move the search element `li.filter` from `ul.multiselect-container` element and place it next to the `button.multiselect` then show/hide the the search element rely on Dropwdown events:
`$("#selectElement").multiselect({
	enableFiltering: true,
	onDropdownShown: function () {
		$("li.filter").show();
	},
	onDropdownHidden: function () {
		$("li.filter").hide();
	},
	enableCaseInsensitiveFiltering: true
});
$("li.filter").insertAfter("button.multiselect").hide();`

**Comment by jvcunha** [comment] 2018-03-21 22:03
no have solution?

**Comment by aftab-currency** [comment] 2019-08-07 09:11
I have fixed this using css.
`.multiselect-filter 
{
  position: sticky;
  top: 5px;
  z-index: 1;
}`

**Comment by LucasRoquilly** [comment] 2021-07-27 16:23
> I have fixed this using css.
> `.multiselect-filter { position: sticky; top: 5px; z-index: 1; }`

Did not work for me. But it works when applying to first line of results : 
`.multiselect-container > li:first-of-type { position: sticky; top: 0px; z-index: 1; }`

**Comment by davidstutz** [comment] 2021-08-02 18:34
Thanks @LucasRoquilly, this worked for me - just needed to adapt it to the current structure. Will include an examples in the documentation and finally close this issues as I do not expect this to become a feature if it can easily be achieved with a bit of CSS.

**Closed** 2021-08-02 18:36 UTC
Labels: bug

**Comment by markusd1984** [comment] 2023-01-10 14:00
> > I have fixed this using css.
> > `.multiselect-filter { position: sticky; top: 5px; z-index: 1; }`
> 
> Did not work for me. But it works when applying to first line of results : `.multiselect-container > li:first-of-type { position: sticky; top: 0px; z-index: 1; }`

Nice thanks! Is it possible also to prevent the search to appear above the field, to always appear underneath? 
Or better increase the minimum available vertical space required before placing it above?

@davidstutz ?
