### ISSUE TITLE
participate in cdnjs

### ISSUE THREAD

**Issue by AlanKrueger** [davidstutz/bootstrap-multiselect#477] opened 2015-01-28 06:34 UTC
Getting this published via https://github.com/cdnjs/cdnjs would allow bootstrap-multiselect to be pulled in via CDN.

**Comment by davidstutz** [comment] 2015-02-12 23:17
Sounds good! Will have a look.

**Comment by davidstutz** [comment] 2016-04-18 18:59
Duplicate of #369.

**Closed by davidstutz** 2016-04-18 18:59 UTC
