### ISSUE TITLE
When tested on IE8, there is an error in line 1430 

### ISSUE THREAD

**Issue by akityou** [davidstutz/bootstrap-multiselect#712] opened 2016-03-02 07:54 UTC
The code of line 1430 is:

class: option.class,

On IE8, it seems that "class" is a key word. I worked around this issue by commented this line.

/*class: option.class,*/

It works for my test case by this way.

**Comment by davidstutz** [comment] 2016-04-17 13:43
Duplicate of #696 and #669.

**Comment by davidstutz** [comment] 2016-04-19 20:42
merged #713.

**Closed** 2016-04-19 20:42 UTC
Labels: bug
