### ISSUE TITLE
Uncaught SyntaxError: Unexpected strict mode reserved word

### ISSUE THREAD

**Issue by tomaskikutis** [davidstutz/bootstrap-multiselect#706] opened 2016-02-24 12:01 UTC
https://github.com/davidstutz/bootstrap-multiselect/blob/master/dist/js/bootstrap-multiselect.js#L1430

$tag = $('<option/>').attr({
	value: option.value,
	label: option.label || option.value,
	title: option.title,
	class: option.class, // <--- --- --- --- --- --- --- --- --- --- --- --- --- --- ---
	selected: !!option.selected,
	disabled: !!option.disabled
});

**Comment by davidstutz** [comment] 2016-04-17 13:08
Duplicate of #669. Will look into it.

**Comment by davidstutz** [comment] 2016-04-19 20:43
Merged #713.

**Closed by davidstutz** 2016-04-19 20:43 UTC
Labels: bug
